### ISSUE TITLE
Library not updated - will this repository be maintained? Can it be used in production?

### ISSUE THREAD

**Issue by rwunsch** [adobe/aem-headless-client-nodejs#15]
This library/client has not been updated since 2 years. 

Will this library/client be maintained in the future?
Can this library be used in production? 
Or should this library be seen as "example implementation" to be using GraphQL?

**Comment by easingthemes** [comment]
This package is fully functional and PROD ready.
- Maintenance is mostly updating dependencies, core functionality stays unchanged.
- Bug Fixing only if a user reports an issue and it's a valid bug.
- Feature updates - only if AEM GraphQL changes
